### ISSUE TITLE
Task-1

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [SreekanthJos/NativeJSTasks#1]
Note:
1. Better to use single var pattern, instead of having multiple var declarations.
2. Better readability purpose use single return statement in a function.
3. Better readability purpose use proper braces for statements.

**Print Array Element:**
1. Array.toString() also joins the array elements with ',' separator.

**TransportOnVacation:**
1.  Use **If else** Or **switch** statements instead of multiple **If** statements

    `if(d>=7)    
        totalCost -= 50;  
      if(d>=3)
        totalCost -= 20;`
In above code when `d = 8` both the if conditons would be true, totalCost would be wrongly calculated.

**Comment by SreekanthJos** [comment]
Modified code according the comments, please verify.
