### ISSUE TITLE
Task-2

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [SreekanthJos/NativeJSTasks#2]
1. Missing single var pattern.

**MiddleCharacter**
1. Math.floor is not needed in this case, (s.length%2) return either 1 or 0.

**PartisionOn**
1. var truthCollection=items.filter(function(i){return pred(i);}); 
    the function inside filter is calling the predicate function itself, it can be replaced as below
    
    ` truthCollection = items.filter(pred);` 

**WordCount**
1. Better to split the conditions for better readability, understandable purpose.

**Comment by SreekanthJos** [comment]
Fixed issues, please review.
